"""Data model of the detected-PII registry — block B5, persistence.

Design and rationale in ``doc/sections/5_architettura.tex``
(§``sec:persistenza-registro``): a delta-based hybrid changelog, with a mutable
current state (:class:`PIIInstance`) alongside an append-only log of what changed
(:class:`PIIChange`), tied to the :class:`Scan` that observed it and the
:class:`Document` it belongs to.

The classes are SQLModel tables (``table=True``): domain object and storage
schema at once (Active Record), like the ROPA model (:mod:`pii_detection.ropa.types`).

**Data minimization (cardinal constraint).** The registry stores only
*references* to PII — their ``pii_type``, position and owning document — and
**never their value**. The value carried by a
:class:`~pii_detection.detection.types.PIIMatch` (``text``) is dropped at this
persistence boundary: no column here can hold it. A compliance registry must not
itself become an archive of personal data.

This module implements **Step 1** (population): every scan records its findings
as :attr:`ChangeType.NEW`. The delta on re-scan (``CONFIRMED``/``MOVED``/
``REMOVED``, with a non-null ``previous_scan``) is Step 2.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from sqlalchemy import JSON, Column
from sqlmodel import Field, Relationship, SQLModel


def _utcnow() -> datetime:
    """:returns: the current UTC time (default for the timestamp columns)."""
    return datetime.now(timezone.utc)


class ChangeType(str, Enum):
    """What happened to a PII instance between one scan and the next.

    Closed vocabulary (``doc/sections/5_architettura.tex``
    §``sub:persistenza-punti-aperti``). Step 1 only ever produces :attr:`NEW`.

    :cvar NEW: instance detected for the first time.
    :cvar CONFIRMED: known instance, found again unchanged (Step 2).
    :cvar MOVED: known instance, found again at a different position (Step 2).
    :cvar REMOVED: known instance, no longer present (Step 2).
    """

    NEW = "new"
    CONFIRMED = "confirmed"
    MOVED = "moved"
    REMOVED = "removed"


class Document(SQLModel, table=True):
    """A scanned document — the container of the PII instances found in it.

    :ivar document_id: stable identifier of the document (primary key); the file
        stem, matching :class:`~pii_detection.detection.types.NormalizedDocument`.
    :ivar path: original path, kept for reference; ``None`` if not provided.
    :ivar first_seen: when the document was first recorded.
    :ivar activity_ids: the declared processing activities this document belongs
        to (block B6, assigned by the DPO). A set, so a document may relate to
        several activities (N:N); the ids reference
        :class:`~pii_detection.ropa.types.ProcessingActivity` in the separate ROPA
        database — there is no physical foreign key across the two databases.
    :ivar source_modified_at: last-modified time of the source file at ingestion
        (its ``mtime``), used as the document's reference date for the approximate
        retention check (B7); a *reference*, not a PII value. ``None`` if unknown.
    :ivar instances: the PII instances contained in this document.
    """

    __tablename__ = "registry_document"

    document_id: str = Field(primary_key=True)
    path: str | None = None
    first_seen: datetime = Field(default_factory=_utcnow)
    activity_ids: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    source_modified_at: datetime | None = None

    instances: list["PIIInstance"] = Relationship(
        back_populates="document",
        sa_relationship_kwargs={"lazy": "selectin", "cascade": "all, delete-orphan"},
    )


class Scan(SQLModel, table=True):
    """One observation of a document at a point in time.

    :ivar id: autogenerated primary key.
    :ivar document_id: the document this scan observed (foreign key).
    :ivar created_at: when the scan ran.
    """

    __tablename__ = "registry_scan"

    id: int | None = Field(default=None, primary_key=True)
    document_id: str = Field(foreign_key="registry_document.document_id")
    created_at: datetime = Field(default_factory=_utcnow)


class PIIInstance(SQLModel, table=True):
    """A single PII found in a document — the current, mutable state.

    Holds only *references*: never the detected value (minimization). The
    position is the character interval in the normalized text, a pointer into the
    document, not its content.

    :ivar id: autogenerated primary key.
    :ivar document_id: the document that contains it (foreign key).
    :ivar pii_type: category from the catalog, e.g. ``"iban"``.
    :ivar start: start offset in the normalized text (inclusive).
    :ivar end: end offset in the normalized text (exclusive).
    :ivar confidence: aggregated confidence in ``[0, 1]``.
    :ivar confirmation_level: merge outcome, e.g. ``"double_confirmed"``.
    :ivar sources: ids of the detectors that found it (traceability, §2.7.3).
    :ivar processing_activity_id: the declared activity it corresponds to, or
        ``None`` if orphan; populated later by the association block (B6), hence
        no foreign key here.
    :ivar last_scan_id: the last scan that observed it (foreign key).
    :ivar removed: whether the instance is no longer present; set by the Step-2
        delta logic, ``False`` on first record.
    :ivar document: back-reference to the owning document.
    :ivar changes: the append-only history of this instance.
    """

    __tablename__ = "registry_pii_instance"

    id: int | None = Field(default=None, primary_key=True)
    document_id: str = Field(foreign_key="registry_document.document_id")
    pii_type: str
    start: int
    end: int
    confidence: float
    confirmation_level: str
    sources: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    processing_activity_id: str | None = None
    last_scan_id: int | None = Field(default=None, foreign_key="registry_scan.id")
    removed: bool = False

    document: Optional["Document"] = Relationship(back_populates="instances")
    changes: list["PIIChange"] = Relationship(
        back_populates="instance",
        sa_relationship_kwargs={"lazy": "selectin", "cascade": "all, delete-orphan"},
    )


class PIIChange(SQLModel, table=True):
    """An entry in the append-only log — what happened to an instance and when.

    :ivar id: autogenerated primary key.
    :ivar pii_instance_id: the instance this change concerns (foreign key).
    :ivar change_type: the kind of variation (closed vocabulary).
    :ivar scan_id: the scan that produced this change (foreign key).
    :ivar previous_scan_id: the previous scan of the same document — what links
        detections over time; ``None`` for the first scan (bootstrap).
    :ivar timestamp: when the change was recorded.
    :ivar instance: back-reference to the owning instance.
    """

    __tablename__ = "registry_pii_change"

    id: int | None = Field(default=None, primary_key=True)
    pii_instance_id: int | None = Field(
        default=None, foreign_key="registry_pii_instance.id"
    )
    change_type: ChangeType
    scan_id: int | None = Field(default=None, foreign_key="registry_scan.id")
    previous_scan_id: int | None = Field(default=None, foreign_key="registry_scan.id")
    timestamp: datetime = Field(default_factory=_utcnow)

    instance: Optional["PIIInstance"] = Relationship(back_populates="changes")


__all__ = [
    "ChangeType",
    "Document",
    "Scan",
    "PIIInstance",
    "PIIChange",
]
