"""Test del modello dati condiviso (Step 1)."""

from __future__ import annotations

import pytest

from pii_detection.detection.types import (
    ConfirmationLevel,
    DetectionProvenance,
    DetectorKind,
    PIIMatch,
    TextSpan,
)


def _provenance(pii_type: str = "iban", confidence: float = 0.9) -> DetectionProvenance:
    return DetectionProvenance(
        detector_id="regex.iban_v1",
        detector_kind=DetectorKind.REGEX,
        pii_type=pii_type,
        confidence=confidence,
    )


class TestTextSpan:
    def test_rejects_empty_or_inverted(self) -> None:
        with pytest.raises(ValueError):
            TextSpan(5, 5)
        with pytest.raises(ValueError):
            TextSpan(5, 3)

    def test_rejects_negative_start(self) -> None:
        with pytest.raises(ValueError):
            TextSpan(-1, 3)

    def test_len(self) -> None:
        assert len(TextSpan(2, 7)) == 5

    def test_is_frozen(self) -> None:
        span = TextSpan(0, 3)
        with pytest.raises(Exception):
            span.start = 1  # type: ignore[misc]

    @pytest.mark.parametrize(
        ("a", "b", "expected"),
        [
            ((0, 10), (5, 15), True),  # sovrapposti
            ((0, 5), (5, 10), False),  # adiacenti, non sovrapposti
            ((0, 5), (6, 10), False),  # disgiunti
        ],
    )
    def test_overlaps(self, a: tuple[int, int], b: tuple[int, int], expected: bool) -> None:
        assert TextSpan(*a).overlaps(TextSpan(*b)) is expected

    def test_overlap_ratio_identical(self) -> None:
        assert TextSpan(0, 10).overlap_ratio(TextSpan(0, 10)) == 1.0

    def test_overlap_ratio_disjoint(self) -> None:
        assert TextSpan(0, 5).overlap_ratio(TextSpan(10, 15)) == 0.0

    def test_overlap_ratio_partial(self) -> None:
        # inter = [5,10) = 5, union = [0,15) = 15 -> 1/3
        assert TextSpan(0, 10).overlap_ratio(TextSpan(5, 15)) == pytest.approx(1 / 3)


class TestProvenance:
    def test_rejects_confidence_out_of_range(self) -> None:
        with pytest.raises(ValueError):
            _provenance(confidence=1.5)
        with pytest.raises(ValueError):
            _provenance(confidence=-0.1)


class TestPIIMatch:
    def test_requires_at_least_one_source(self) -> None:
        with pytest.raises(ValueError):
            PIIMatch(
                span=TextSpan(0, 4),
                text="....",
                pii_type="iban",
                confidence=0.9,
                confirmation_level=ConfirmationLevel.SINGLE_SOURCE,
                sources=[],
                document_id="doc-1",
            )

    def test_match_id_is_autogenerated_and_unique(self) -> None:
        kwargs = dict(
            span=TextSpan(0, 4),
            text="....",
            pii_type="iban",
            confidence=0.9,
            confirmation_level=ConfirmationLevel.SINGLE_SOURCE,
            sources=[_provenance()],
            document_id="doc-1",
        )
        m1 = PIIMatch(**kwargs)  # type: ignore[arg-type]
        m2 = PIIMatch(**kwargs)  # type: ignore[arg-type]
        assert m1.match_id and m2.match_id
        assert m1.match_id != m2.match_id

    def test_enum_value_is_string(self) -> None:
        assert ConfirmationLevel.DOUBLE_CONFIRMED.value == "double_confirmed"
        assert DetectorKind.REGEX.value == "regex"
