"""Data model of the ROPA (Record of Processing Activities) — block B1.

Design and rationale in ``doc/sections/5_architettura.tex`` (§``sec:modello-ropa``).
The model keeps only the declared **categories of personal data**, organized in a
three-level hierarchy that mirrors the CNIL register:

.. code-block:: text

    ProcessingActivity  ──1:N──▶  DeclaredMacroCategory  ──1:N──▶  DeclaredCategory
                                  (+ retention)                    (+ pii_types)

The classes are SQLModel tables (``table=True``): each is at once the domain
object and its storage schema (Active Record). There is no separate set of
persistence rows and no hand-written translation — the structure is defined once.

Two design choices make it fit the compliance-checking purpose (B7) rather than
merely mirroring the source document:

1. **Shared vocabulary (bridge to B4).** :class:`DeclaredCategory` resolves a
   declared category onto the same ``pii_type`` catalog used by the detection
   layer, one-to-many, so comparing what the ROPA *declares* with what the engine
   *finds* becomes a set operation. The AI proposes the mapping, the DPO confirms
   it (:class:`MappingState`).
2. **Machine-computable retention.** :class:`DeclaredMacroCategory` stores a
   structured ``retention_months`` next to the original wording, so the "past
   retention?" check is computable rather than a prose read. Retention lives at
   the macro-category level: the single categories under it inherit it.
"""

from enum import Enum
from typing import Optional

from sqlalchemy import JSON, Column
from sqlmodel import Field, Relationship, SQLModel


class MappingState(str, Enum):
    """Confirmation state of a declared-category → ``pii_type`` mapping.

    :cvar PROPOSED: mapping produced by the selective AI, not yet validated.
    :cvar CONFIRMED: mapping validated by the DPO; safe to use for compliance.
    """

    PROPOSED = "proposed"
    CONFIRMED = "confirmed"


class DeclaredCategory(SQLModel, table=True):
    """A single declared data category — level 3, the bridge to the detection layer.

    The atomic entry found in the register, or split/enriched out of a macro
    category by rules or AI. Its ``pii_types`` resolve it onto the shared catalog
    so B7 can compare declared vs detected. The mapping is machine-proposed and
    DPO-confirmed (:class:`MappingState`), never fixed by the AI alone.

    :ivar id: autogenerated primary key.
    :ivar macro_category_id: macro category this one belongs to (foreign key).
    :ivar raw_text: original free-text category, kept for audit (``"nome"``).
    :ivar pii_types: catalog ids it resolves to, possibly empty (not mapped yet).
    :ivar mapping_state: whether the mapping is AI-proposed or DPO-confirmed.
    :ivar macro_category: back-reference to the owning macro category.
    """

    __tablename__ = "declared_category"

    id: int | None = Field(default=None, primary_key=True)
    macro_category_id: int | None = Field(default=None, foreign_key="macro_category.id")
    raw_text: str
    pii_types: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    mapping_state: MappingState = MappingState.PROPOSED

    macro_category: Optional["DeclaredMacroCategory"] = Relationship(back_populates="categories")


class DeclaredMacroCategory(SQLModel, table=True):
    """A macro category grouping single categories under a shared retention — level 2.

    Mirrors a CNIL data-category block. Holds the retention rule that its
    :attr:`categories` inherit; ``retention_months`` is the machine-computable
    duration next to the original wording.

    :ivar id: autogenerated primary key.
    :ivar activity_id: activity this macro category belongs to (foreign key).
    :ivar raw_text: original macro-category wording, kept for audit.
    :ivar retention_text: original retention wording, kept for audit.
    :ivar retention_months: retention length in months; ``None`` when the register
        states a criterion rather than a fixed duration.
    :ivar categories: the single declared categories grouped under it.
    :ivar activity: back-reference to the owning processing activity.
    """

    __tablename__ = "macro_category"

    id: int | None = Field(default=None, primary_key=True)
    activity_id: str | None = Field(default=None, foreign_key="processing_activity.id")
    raw_text: str
    retention_text: str
    retention_months: int | None = None

    categories: list[DeclaredCategory] = Relationship(
        back_populates="macro_category",
        sa_relationship_kwargs={"lazy": "selectin", "cascade": "all, delete-orphan"},
    )
    activity: Optional["ProcessingActivity"] = Relationship(back_populates="macro_categories")


class ProcessingActivity(SQLModel, table=True):
    """A single processing activity — level 1, the top of the hierarchy.

    Mirrors one CNIL processing record, reduced to its identity and the declared
    data categories: the register exists here to answer "which categories of
    personal data are declared?", which is what B7 checks.

    :ivar id: stable identifier of the activity (primary key, caller-assigned).
    :ivar name: name of the processing activity.
    :ivar purpose: declared purpose.
    :ivar macro_categories: the macro categories declared by this activity.
    """

    __tablename__ = "processing_activity"

    id: str = Field(primary_key=True)
    name: str
    purpose: str

    macro_categories: list[DeclaredMacroCategory] = Relationship(
        back_populates="activity",
        sa_relationship_kwargs={"lazy": "selectin", "cascade": "all, delete-orphan"},
    )

__all__ = [
    "MappingState",
    "DeclaredCategory",
    "DeclaredMacroCategory",
    "ProcessingActivity",
]